## 案例: 演示张量的基本运算.

涉及到的API:

    add(), sub(), mul(), div(), neg()       -> 加减乘除, 取反, substract, multiply, divide
    add_(), sub_(), mul_(), div_(), neg_()  -> 功能同上, 只不过可以修改源数据, 类似于 Pandas部分的 inplace = True

需要记忆的:

    1. 可以用 +, -, *, / 符号来替代 上述的 加减乘除函数.
    2. 如果是张量 和 数值运算, 则: 该数值会和张量中的每个值依次进行 对应的运算.

#### 导包

In [1]:
import numpy as np
import torch

#### 1. 创建张量

In [2]:
t1 = torch.tensor([1, 2, 3])

# 2. 演示 加法

In [3]:
t2 = t1.add(10)      # 不会修改源数据.
# t2 = t1 + 10         # 效果同上.
print(t1)
print(t2)

t1.add_(10)            # 会修改源数据.
# t1 += 10               # 效果同上
print(t1)

tensor([1, 2, 3])
tensor([11, 12, 13])
tensor([11, 12, 13])


#### 3. 其它函数效果同上

In [4]:
t3 = t1.sub(1)      # 减法
print(t3)
t4 = t1.mul(2)      # 乘法
print(t4)
t5 = t1.div(2)      # 除法
print(t5)
t6 = t1.neg()         # 取反
print(t6)

tensor([10, 11, 12])
tensor([22, 24, 26])
tensor([5.5000, 6.0000, 6.5000])
tensor([-11, -12, -13])
