#### 案例: 演示 张量的 索引操作.

分类:

    简单行列索引
    列表索引
    范围索引
    布尔索引
    多维索引

掌握:

    简单行列索引, 范围索引, 多维索引.

#### 导包

In [1]:
import numpy as np
import torch

#### 1. 设置随机种子

In [2]:
torch.manual_seed(24)

#### 2. 创建随机张量

In [3]:
# 创建一个 5 行 5 列的随机整数张量, 范围在 [1, 10) 之间
t1 = torch.randint(1, 10, (5, 5))
print(f't1: {t1}')

t1: tensor([[6, 9, 9, 2, 8],
        [7, 8, 5, 8, 4],
        [7, 4, 3, 9, 3],
        [6, 1, 4, 2, 8],
        [1, 2, 5, 7, 4]])


#### 3. 演示张量的索引操作

In [4]:
# 场景1: 简单行列索引, 格式: 张量对象[行, 列]
# 需求1: 获取索引第1行的数据
print(t1[1])
print(t1[1, :])  # 效果同上, 这里的:表示 所有列
print('-' * 50)

# 需求2: 所有行的索引第2列数据
print(t1[:, 2])

tensor([7, 8, 5, 8, 4])
tensor([7, 8, 5, 8, 4])
--------------------------------------------------
tensor([9, 5, 3, 4, 5])


In [5]:
# 场景2: 列表索引, 前边的表示行, 后边的表示列
# 需求1: 返回(0, 1), (1, 2)两个位置的元素, 凑巧
print(t1[[0, 1], [1, 2]])
print('-' * 50)

# 需求2: 返回(1, 2), (3, 4)两个位置的元素
# 注意: 这里的列表索引是按照位置进行索引的, 而不是按照行列进行索引的
# 这里的[1, 3]表示索引的行位置, [2, 4]表示索引的列位置, 最终返回的是(1, 2)和(3, 4)两个位置的元素
print(t1[[1, 3], [2, 4]])
print('-' * 50)

# 需求3: 获取第0, 1行的 1, 2列共4个元素.
print(t1[[[0], [1]], [1, 2]])

tensor([9, 5])
--------------------------------------------------
tensor([5, 8])
--------------------------------------------------
tensor([[9, 9],
        [8, 5]])


In [6]:
# 场景3: 范围索引
# 需求1: 前3行, 前2列
print(t1[:3, :2])
print('-' * 50)

# 需求2: 第2行（索引为1）到最后一行, 前2列的数据
print(t1[1:, :2])
print('-' * 50)

# 需求3: 所有奇数行, 偶数列
# 注意: 这里的1::2表示从第1行开始, 每隔2行取一次, 也就是取第1行, 第3行, 第5行等奇数行; 
# ::2表示从第0列开始, 每隔2列取一次, 也就是取第0列, 第2列, 第4列等偶数列
print(t1[1::2, ::2])

tensor([[6, 9],
        [7, 8],
        [7, 4]])
--------------------------------------------------
tensor([[7, 8],
        [7, 4],
        [6, 1],
        [1, 2]])
--------------------------------------------------
tensor([[7, 5, 4],
        [6, 4, 8]])


In [7]:
# 场景4: 布尔索引
# 获取第0, 3, 4行的所有列数据
print(t1[torch.tensor([True, False, False, True, True]), :])    # 演示布尔写法, 看看就好.
print('-' * 50)

# 需求1: 第3列（索引为2） 大于5的行数据
# 先看第3列哪个数大于5，然后把这个数所在的行都打印出来
# t1[:, 2] > 5表示在所有行第3列（索引为2）中找到大于5的元素，并返回一个布尔数组，
# 表示哪些行中的第3列元素大于5；t1[t1[:, 2] > 5]表示在t1中找到这些行，并返回这些行的数据
print(t1[t1[:, 2] > 5])
print('-' * 50)

# 需求2: 第2行（索引为1）大于5的 列数据
# 理解1: 在第2行（索引为1）基础上 找到该行中大于5的列索引, 然后找所有行中对应列的元素
# t1[1, :] > 5中，"1"表示取第2行，":"表示取该行的所有列，"> 5"表示判断这些列中的元素是否大于5，
# 最终返回的是一个布尔数组，表示哪些列中的元素大于5
# t1[:, t1[1, :] > 5]中，第一个":"表示取所有行，t1[1, :] > 5表示在第2行（索引为1）中找到大于5的元素，
# 并返回这些元素所在的列索引，最终返回的是所有行中对应列索引的元素
print(t1[:, t1[1, :] > 5])
print(t1[:, t1[1] > 5])     # 效果同上
print('-' * 30)

# 理解2: 在第2行（索引为1）的基础上, 找该行所有列中大于5的元素
print(t1[1, t1[1, :] > 5])

tensor([[6, 9, 9, 2, 8],
        [6, 1, 4, 2, 8],
        [1, 2, 5, 7, 4]])
--------------------------------------------------
tensor([[6, 9, 9, 2, 8]])
--------------------------------------------------
tensor([[6, 9, 2],
        [7, 8, 8],
        [7, 4, 9],
        [6, 1, 2],
        [1, 2, 7]])
tensor([[6, 9, 2],
        [7, 8, 8],
        [7, 4, 9],
        [6, 1, 2],
        [1, 2, 7]])
------------------------------
tensor([7, 8, 8])


In [8]:
# 场景5: 多维索引
# 创建3维张量, 即: 2个3行4列的矩阵
t2 = torch.randint(1, 10, (2, 3, 4))
print(f't2: {t2}')
print('-' * 50)

# 需求1: 获取0轴上的第1个数据
# 即: 获取第1个3行4列的矩阵
print(t2[0, :, :])
print('-' * 50)

# 需求2: 获取1轴上的第1个数据
# 即：获取所有3行4列的矩阵中的第1行数据
print(t2[:, 0, :])
print('-' * 50)

# 需求3: 获取2轴上的第1个数据
# 即：获取所有3行4列的矩阵中的第1列数据
print(t2[:, :, 0])

t2: tensor([[[3, 4, 6, 5],
         [8, 8, 8, 3],
         [4, 9, 6, 7]],

        [[2, 8, 8, 5],
         [6, 4, 2, 2],
         [2, 7, 9, 4]]])
--------------------------------------------------
tensor([[3, 4, 6, 5],
        [8, 8, 8, 3],
        [4, 9, 6, 7]])
--------------------------------------------------
tensor([[3, 4, 6, 5],
        [2, 8, 8, 5]])
--------------------------------------------------
tensor([[3, 8, 4],
        [2, 6, 2]])
